#include "hardware.h"
#include "firmware.h"
#include <Arduino.h>
#include <Preferences.h>

Preferences hwPrefs;

bool hwEnabled[HW_ENABLED_SIZE];

void calcHwPrefs() {
    OBSCON_RAINRATE =  HARDWARE_UICPAL || HARDWARE_RG15;
    OBSCON_TEMPERATURE = HARDWARE_BMP280 || HARDWARE_AHT20 || HARDWARE_SHT45;
    OBSCON_HUMIDITY = HARDWARE_AHT20 || HARDWARE_SHT45;
    OBSCON_DEWPOINT = OBSCON_TEMPERATURE && OBSCON_HUMIDITY;
    OBSCON_PRESSURE = HARDWARE_BMP280;
    OBSCON_SKYTEMP = HARDWARE_MLX90614;
    OBSCON_CLOUDCOVER = HARDWARE_MLX90614;
    OBSCON_FWHM = HARDWARE_MLX90614;
    OBSCON_SKYBRIGHTNESS = HARDWARE_TSL2591;
    OBSCON_SKYQUALITY = HARDWARE_TSL2591;
    OBSCON_WINDDIR = false;
    OBSCON_WINDSPEED = HARDWARE_ANEMO4403;
    OBSCON_WINDGUST = HARDWARE_ANEMO4403;

    SAFEMON_RAINRATE = HARDWARE_UICPAL || HARDWARE_RG15;
    SAFEMON_TEMPERATURE = HARDWARE_BMP280 || HARDWARE_AHT20 || HARDWARE_SHT45;
    SAFEMON_HUMIDITY = HARDWARE_AHT20 || HARDWARE_SHT45;
    SAFEMON_DEWPOINT = SAFEMON_TEMPERATURE && SAFEMON_HUMIDITY;
    SAFEMON_SKYTEMP = HARDWARE_MLX90614;
    SAFEMON_WINDSPEED = HARDWARE_ANEMO4403;
}

void initHwPrefs() {
    hwPrefs.begin("hwPrefs", false);
    // Default values for current firmware
    std::fill(std::begin(hwEnabled), std::end(hwEnabled), false);
    HARDWARE_DS3231 = FIRMWARE_DS3231;
    HARDWARE_BMP280 = FIRMWARE_BMP280;
    HARDWARE_AHT20 = FIRMWARE_AHT20;
    HARDWARE_SHT45 = FIRMWARE_SHT45;
    HARDWARE_MLX90614 = FIRMWARE_MLX90614;
    HARDWARE_TSL2591 = FIRMWARE_TSL2591;
    HARDWARE_UICPAL = FIRMWARE_UICPAL;
    HARDWARE_ANEMO4403 = FIRMWARE_ANEMO4403;
    HARDWARE_RG15 = FIRMWARE_RG15;
    ALPACA_OBSCON = FIRMWARE_ALPACA_OBSCON;
    ALPACA_SAFEMON = FIRMWARE_ALPACA_SAFEMON;
    calcHwPrefs();
    loadHwPrefs();
}

void loadHwPrefs() {
    if (hwPrefs.isKey("hardware")) {
        hwPrefs.getBytes("hardware", hwEnabled, sizeof(hwEnabled));
        calcHwPrefs();
    }
}

void saveHwPrefs() {
    calcHwPrefs();
    hwPrefs.putBytes("hardware", hwEnabled, sizeof(hwEnabled));
}
